### ISSUE TITLE
Homework 2 Feedback

### ISSUE THREAD

**Issue by HeyStenson** [kristincox/Wendy_Resume#1]
Well done! :palm_tree: 

**Readability of your code (1-3):**
2.5 - Make sure the indentation indicates the hierarchy of your code! Here I'm thinking specifically about the <p> tags in the jobs section of the resume.
**Does it run? (1-3):**
3
**Are best practices followed? (1-3):**
3

**Notes:**
While it's not against the rules to link to two separate stylesheets, in most cases it's better to use one - especially since there are so many similarities between index.html and resume.html!

**Comment by kristincox** [comment]
Hi Heather,

Thanks for your feedback and also for your help last week.

See you tonight!

Kristin
